name: gestorfy_cliente
description: "Visualizador de orÃ§amentos para clientes Gestorfy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  
  # UI/UX
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  
  # Utilities
  url_launcher: ^6.3.1
  share_plus: ^10.1.0
  deep_link:
    git:
      url: https://github.com/REU8ER/deep-link.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/